### PR TITLE
Fix SMS restoration on android 14

### LINKED ISSUE #99: 恢复短信失效
Write your issue description here.
开发者你好，我前些天反馈的Android 14无法拦截来信时得到了及时解决，但是没注意测试拦截后的恢复情况，刚才想恢复一条运营商的业务短信时发现点击了恢复，但是短信APP里看不到恢复的短信了。麻烦排查一下问题？
---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device:  Pixel 5
- Android version:  Android 14
- Xposed version: 1.9.2 (7024)
- NekoSMS version: 0.22.0

Please upload your Xposed logs below (drag & drop into this box):

[LSPosed_2023-10-21T18_25_08.478722.zip](https://github.com/apsun/NekoSMS/files/13060475/LSPosed_2023-10-21T18_25_08.478722.zip)

### PR DESCRIPTION
**Pull request by NekoGirlSAIKOU**
Fix #99

### CODE REVIEW

**Comment by apsun** [comment]
Thanks for the PR! Do you have a reference (code link, etc) for why this causes restoring to fail? I'd like to link to that for posterity

**Comment by NekoGirlSAIKOU** [comment]
According to #89, the subId stored in NekoSMS database is all 0 since Android 11.  According to his screenshot, the SMS App don't recognize related SIM card for restored SMS with subId 0. So 0 may be an invalid subId. While debugging this bug, because of `E TelephonyPermissions: Subscription[Subscription ID:0] has no records on device
` in logs, I tried not to restore the subId and found the problem solved. 

不太擅长英语写作，表达不太清楚。还是用中文重新写一遍好了。。。根据 #89 这个PR在Android 11之后NekoSMS记录的拦截的短信的subId全部都是0。而且根据他的截图，subId为0的短信还原后，在短信App中还是无法正确的识别出对应的SIM卡，所以我觉着0可能是无效的subId。而且我在我的手机上调试时，尝试还原短信的时候系统报了`E TelephonyPermissions: Subscription[Subscription ID:0] has no records on device
`这个错误，所以我就只管试着在subId为0时不还原subId试试，结果就可以正常还原短信了。我猜为0的subId可能本身是合法的，但是因为我的手机上的SIM卡的subId都不为0，所以还原短信时系统找不到对应的SIM卡，Android 14之前可能找不到的话就忽略了，Android 14可能更严格改为报错了（虽然大致看了下Android 14的行为变更也没找到相关的变更...）。当时没想那么多（我当时以为0是完全无效的subId...），也许更正确的修复方式是检查下是否有与subId对应为的SIM卡来决定是否还原这一项？最根本的解决方式应该是合并 #89，不过对于subId为0的旧记录应该还是要额外处理下。

**Comment by NekoGirlSAIKOU** [comment]
翻了下LineageOS 21.0(Android 14)的代码（不知道怎么在android.googlesource.com上进行搜索...而且我用的ROM是基于LineageOS的所以先看了这个）这个报错是[TelephonyPermissions](https://github.com/LineageOS/android_frameworks_base/blob/lineage-21.0/telephony/common/com/android/internal/telephony/TelephonyPermissions.java)中的[checkSubscriptionAssociatedWithUser](https://github.com/LineageOS/android_frameworks_base/blob/3e39d48f004ee398276ff3d3a53e3577d123f9c2/telephony/common/com/android/internal/telephony/TelephonyPermissions.java#L887)这个方法输出的，并且在LineageOS 20.0(Android 13)的[TelephonyPermissions.java](https://github.com/LineageOS/android_frameworks_base/blob/lineage-20.0/telephony/common/com/android/internal/telephony/TelephonyPermissions.java)中没有这个方法。最后可能是因为在LineageOS 21.0的[SmsProvider.java](https://github.com/LineageOS/android_packages_providers_TelephonyProvider/blob/lineage-21.0/src/com/android/providers/telephony/SmsProvider.java)中的[insertInner](https://github.com/LineageOS/android_packages_providers_TelephonyProvider/blob/b87ec340fe67c18f28b768c32997f778e189d06f/src/com/android/providers/telephony/SmsProvider.java#L642)方法里调用了`checkSubscriptionAssociatedWithUser`方法进行检查，然后因为检查没通过于是没有把短信写入数据库。

不过AOSP的Android 14中的`SmsProvider.java`的[insertInner](https://android.googlesource.com/platform/packages/providers/TelephonyProvider/+/refs/heads/android14-release/src/com/android/providers/telephony/SmsProvider.java#706)方法中虽然似乎也调用了`checkSubscriptionAssociatedWithUser`这个方法但AOSP的[TelephonyPermissions.java](https://android.googlesource.com/platform//frameworks/base/+/refs/heads/android14-release/telephony/common/com/android/internal/telephony/TelephonyPermissions.java)中虽然有`checkSubscriptionAssociatedWithUser`这个方法但似乎没有no records这个报错，也许这是LineageOS自己加的检查？不过我也没有别的Android 14的设备了没法检查在AOSP上的行为。。。

可能AOSP上不会这样，又看了下AOSP的且`SubscriptionManager.java`的[isSubscriptionAssociatedWithUser](https://android.googlesource.com/platform//frameworks/base/+/refs/heads/android14-release/telephony/java/android/telephony/SubscriptionManager.java#4292)方法和LineageOS的[isSubscriptionAssociatedWithUser](https://github.com/LineageOS/android_frameworks_base/blob/3e39d48f004ee398276ff3d3a53e3577d123f9c2/telephony/java/android/telephony/SubscriptionManager.java#L4701)方法。貌似都是在调用`isValidSubscriptionId(subscriptionId)`来检查是否有效，无效的话抛出`IllegalArgumentException`异常。只是LineageOS在`checkSubscriptionAssociatedWithUser`方法中捕获了这个异常，但AOSP没有捕获这个异常。不过奇怪的是`isValidSubscriptionId`都是检查是否大于-1的，只要大于-1就认为有效，所以AOSP和LineageOS都不应该在这里抛出异常才对。但AOSP对`isSubscriptionAssociatedWithUser`的注释是`@throws IllegalArgumentException if subscription is invalid.`而LineageOS的注释是`@throws IllegalArgumentException if subscription doesn't exist.`，所以我猜应该是别的地方的代码抛出的这个异常。也许是`iSub.isSubscriptionAssociatedWithUser`抛的？但是没找到它的代码。。。

**Comment by apsun** [comment]
Ok, I think I understand now. Any subId which is invalid will fail (not just 0), but [`SmsMessageUtils#getSubId`](https://github.com/apsun/NekoSMS/blob/master/app/src/main/java/com/crossbowffs/nekosms/utils/SmsMessageUtils.java#L31) was broken and always returning 0, and so now messages in our database have an invalid subId value

Although I guess that's not the only source of subId == 0; https://github.com/apsun/NekoSMS/blob/master/app/src/main/java/com/crossbowffs/nekosms/provider/DatabaseHelper.java#L132 also initializes it to 0 if upgrading from an older app version without multi-SIM support

I missed #89 (sorry!), will take a look at that. As a workaround for the bad values in our database though, I think this PR is a fair mitigation (other option would be to retry rejected insert without the subId value). Thank you!

**Comment by apsun** [comment]
Figured it out, `getSubId` is useless as of https://android-review.googlesource.com/c/platform/frameworks/base/+/1196441, the field is never initialized so we always get 0

**Comment by apsun** [comment]
Could you give this build a try and report back if restore still works? It changes the default value from 0 to -1 and updates the existing values in the db. Unfortunately it's not possible to tell whether 0 was an actual value so it throws away the subId information for existing messages.

[NekoSMS-0.23.0-dev.zip](https://github.com/user-attachments/files/16048707/NekoSMS-0.23.0-dev.zip)

**Comment by NekoGirlSAIKOU** [comment]
It works for old messages. But new messages still can't be restored. Their subId is still 0.

**Comment by NekoGirlSAIKOU** [comment]
> It works for old messages. But new messages still can't be restored. Their subId is still 0.

It works well. I forgot to reboot my phone...

**Comment by apsun** [comment]
> > It works for old messages. But new messages still can't be restored. Their subId is still 0.
> 
> It works well. I forgot to reboot my phone...

Ah, yeah... I should bump the module version too. It's been a while since I touched it :sweat_smile:

**Pull request merged**
