### PR TITLE
Fix module XposedUtilsHook on Taichi

### PR DESCRIPTION
**Pull request by aviraxp**
* See https://taichi.cool/zh/doc/for-xposed-dev.html#%E6%96%B9%E6%B3%95%E6%8B%A6%E6%88%AA-hook.

### CODE REVIEW

**Comment by apsun** [comment]
Please also add a comment describing why this log exists (I presume it's because it would otherwise be inlined?) Thanks!

**Comment by wyUshio** [comment]
> Please also add a comment describing why this log exists (I presume it's because it would otherwise be inlined?) Thanks!

能帮忙适配下太极*阳吗? 我用edxposed无法使用核心破解.....

**Comment by aviraxp** [comment]
我仔细看了下，XposedUtils类完全没有被加载，只能 @weishu 了

**Comment by aviraxp** [comment]
我怀疑他的模块支持数据库有问题

**Pull request closed without merging**
